[bumpver]
# bumpver configuration: updates pyproject.toml, commits and tags releases.
# Use: `bumpver patch|minor|major` (or integrate into CI/release workflow)
current_version = "1.0.0"
parse = '^(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)$'
serialize = "{major}.{minor}.{patch}"
files = ["pyproject.toml"]
tag = "v{new_version}"
commit = true
message = "chore(release): bump version to {new_version}"