# Cognitive config for GPT-5 learning benchmark
cognitive_system:
  enabled: true

  # Global LLM defaults (can be overridden per sub-system)
  llm:
    model_name: "gpt-5"
    temperature: 0.2
    max_tokens: 4096
    retry_attempts: 3

  hierarchical_planning:
    enabled: true
    depth: 2
    goal_horizon: "annual"
    replan_frequency: "quarterly"
    lookahead_days: 90
    llm_model: "gpt-5"

  reflection:
    enabled: true
    frequency: "end_of_quarter"
    insight_generation: true
    feedback_loop_enabled: true
    max_reflection_tokens: 2500
    min_progress_for_reflection: 0.05
    llm_model: "gpt-5"

  memory:
    enabled: true
    validation: true
    consistency_checks: true
    forgetting_strategy: "least_recent_access"
    max_memory_size: 1000
    long_term_storage_backend: "json_file"
    memory_path: "./memory_data/"
